#!/bin/sh
set -ex

# Run a prebuilt dsp_fw_sim.  This tool was designed to be run from
# its build directory, expects to have Xtensa SDK environment
# variables set that match its build environment and not whatever the
# caller might be using, and it links against libraries with a
# hard-coded path.
#

export XTENSA_CORE=ace30_LX7HiFi4

VER=$XTENSA_TOOLS_VERSION
TOOLS=$XTENSA_TOOLS_DIR

export XTENSA_TOOLS_VERSION="$VER"
export XTENSA_BUILDS_DIR=$(dirname "$TOOLS")/builds
export LD_LIBRARY_PATH="$TOOLS/$VER/XtensaTools/lib64/iss:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$TOOLS/$VER/XtensaTools/lib64:$LD_LIBRARY_PATH"

# Path for our matching xt-gdb, echo this to get the info back to the wrapper
echo "PREBUILT: xt-bin-path: $TOOLS/$VER/XtensaTools/bin"

cd sim_prebuilt
exec ./dsp_fw_sim "$@"
stty sane
