name: Intel Scancode

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scancode_job:
    runs-on: fmos-guest-ubuntu-12c
    name: Scan code for licenses
    steps:
      - name: Clean
        run: |
          shopt -s dotglob
          sudo rm -rf *
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Scan the code
        id: scancode
        uses: zephyrproject-rtos/action_scancode@v4
        with:
          directory-to-scan: 'scan/'
      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        with:
          name: scancode
          path: ./artifacts
      - name: Clean up any leftover files
        run: |
          shopt -s dotglob
          sudo rm -rf *
      - name: Verify
        run: |
          if [ -s ./artifacts/report.txt ]; then
            report=$(cat ./artifacts/report.txt)
            report="${report//'%'/'%25'}"
            report="${report//$'\n'/'%0A'}"
            report="${report//$'\r'/'%0D'}"
            echo "::error file=./artifacts/report.txt::$report"
            exit 1
          fi
